# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
#        FOS\UserBundle\Model\UserInterface: bcrypt
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
#            id: fos_user.user_provider.username_email
            id: fos_user.user_provider.username        # fos_user.user_provider.username_email does not seem to work (OAuth-spec related ("username + password") ?)

    firewalls:
                    
        oauth_token:                                   # Everyone can access the access token URL.
            pattern: ^/api/v1/oauth/v2/token
            security: false
        user_create:
            pattern: ^/api/v1/users
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: true                           # Anonymous access is not allowed
            methods: [POST]
        api:
            pattern: ^/api                             # All URLs are protected
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: false                           # Anonymous access is not allowed
            entry_point: api_authentication_entry_point
        main:
            pattern: ^/
            oauth:
                failure_path: /login
                login_path: /login
                check_path: /connect_check
                provider: fos_userbundle
                resource_owners:
                    facebook: "/fblogin/check-facebook"
                    google: "/fblogin/check-google"
                oauth_user_provider:
                    service: app.provider.oauth

            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/api/v1/users, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [POST]}
        - { path: ^/api/, role: ROLE_USER }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/login/check-facebook, roles: IS_AUTHENTICATED_ANONYMOUSLY }