# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: User }

    admin.facebook_friend:
        class: AppBundle\Admin\FacebookFriendAdmin
        arguments: [~, AppBundle\Entity\FacebookFriend, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: FacebookFriend }

    admin.training:
        class: AppBundle\Admin\TrainingAdmin
        arguments: [~, AppBundle\Entity\Training, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Training }
                        
    admin.sport:
        class: AppBundle\Admin\SportAdmin
        arguments: [~, AppBundle\Entity\Sport, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Sport }
                        
    api_authentication_entry_point:
         class: AppBundle\Entity\Auth\ApiAuthenticationEntryPoint
         arguments: [ api ]
         
    app.provider.oauth:
        class: AppBundle\Entity\Auth\OAuthUserProvider
        arguments: [@fos_user.user_manager,{facebook: facebookID}]

