utils:
    type:     rest
    prefix:   /api/v1
    resource: AppBundle\Controller\UtilController

users:
    type:     rest
    prefix:   /api/v1
    resource: AppBundle\Controller\UsersController

sports:
    type:     rest
    prefix:   /api/v1
    resource: AppBundle\Controller\SportsController

trainings:
    type:     rest
    prefix:   /api/v1
    resource: AppBundle\Controller\TrainingsController

facebook_friends:
    type:     rest
    parent:   users
    resource: AppBundle\Controller\FacebookFriendsController