users:
    type:     rest
    prefix:   /api/v1
    host:     localhost
    resource: AppBundle\Controller\UsersController

facebook_friends:
    type:     rest
    host:     localhost
    parent:   users
    resource: AppBundle\Controller\FacebookFriendsController