utils:
    type:     rest
    prefix:   /api/v1
    host:     localhost
    resource: AppBundle\Controller\UtilController

users:
    type:     rest
    prefix:   /api/v1
    host:     localhost
    resource: AppBundle\Controller\UsersController

sports:
    type:     rest
    prefix:   /api/v1
    host:     localhost
    resource: AppBundle\Controller\SportsController

facebook_friends:
    type:     rest
    host:     localhost
    parent:   users
    resource: AppBundle\Controller\FacebookFriendsController